terms:
- id: Figurative_language
  synonyms:
    synonym1: metonymy
- id: Grammar_Adjectives
  synonyms:
    synonym1: modifier
- id: Grammar_Articles
  synonyms:
    synonym1: determiner
- id: Grammar_Noun_inflections
  synonyms:
    synonym1: "noun endings AND noun agreement"
- id: Grammar_Verb_inflections
  synonyms:
    synonym1: "verb endings AND verb agreement"
- id: Interaction
  synonyms:
    synonym1: "computer mediated"
- id: Phonics_Awareness
  synonyms:
    synonym1: "phonology AND phonetic AND phoneme AND grapheme"
- id: Phonics_Applying_sound_symbol
  synonyms:
    synonym1: "phonology AND phonetic AND phoneme AND grapheme"
- id: Phonics_Consolidating_sound_symbol
  synonyms:
    synonym1: "phonology AND phonetic AND phoneme AND grapheme"
- id: Phonics_Introducing_new_sound_symbol
  synonyms:
    synonym1: "phonology AND phonetic AND phoneme AND grapheme"
- id: Phonics_Isolated_sound_symbol
  synonyms:
    synonym1: "phonology AND phonetic AND phoneme AND grapheme"
- id: Teaching_Methods_Content
  synonyms:
    synonym1: "CLIL"
- id: Teaching_Methods_Task_Based_Language_Teaching
  synonyms:
    synonym1: "TBLT"
- id: Testing
  synonyms:
    synonym1: "assess"
- id: Vocabulary_Adjectives
  synonyms:
    synonym1: "modifier"
- id:
  synonyms:
    synonym1: ""
- id:
  synonyms:
    synonym1: ""
- id:
  synonyms:
    synonym1: ""
- id:
  synonyms:
    synonym1: ""
- id:
  synonyms:
    synonym1: ""
- id:
  synonyms:
    synonym1: ""
