terms:
- id: CPD_powerpoints
  term: "CPD powerpoints & materials"
- id: Criteria_for_selecting_teaching_resources
  term: "Criteria for selecting teaching resources"
- id: Knowledge_about_English_from_KS2
  term: "Knowledge about English from KS2"
- id: Observation_schedules
  term: "Observation schedules"
- id: Principles_ideas_for_teaching_curriculum
  term: "Principles & ideas for teaching & curriculum"
- id: Primary-Secondary_Transition
  term: "Primary-Secondary Transition"
- id: Schemes_of_work
  term: "Schemes of work"
- id: Video_clips_of_classrooms
  term: "Video clips of classrooms"
- id: Vocabulary_frequency_lists
  term: "Vocabulary frequency lists"
- id: Other
  term: Other
