development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= Figaro.env.fedora_url %>
  base_path: <%= Figaro.env.fedora_base_path %>
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= Figaro.env.fedora_url %>
  base_path: <%= Figaro.env.fedora_base_path %>
production:
  user: <%= Figaro.env.fedora_username %>
  password: <%= Figaro.env.fedora_password %>
  url: <%= Figaro.env.fedora_url %>
  base_path: <%= Figaro.env.fedora_base_path %>
