development:
  host: <%= Figaro.env.redis_host %>
  port: <%= Figaro.env.redis_port %>
test:
  host: <%= Figaro.env.redis_host %>
  port: <%= Figaro.env.redis_port %>
production:
  host: <%= Figaro.env.redis_host %>
  port: <%= Figaro.env.redis_port %>
